package com.raychen518.study.spring.core.ioccontainer.classpathscanningandcomponents.definingbeanmetadataincomponents;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;

/**
 * <pre>
 * - Check the class "BeanC3" under the sub-package "somepath" for how to define the bean metadata in a component.
 * - Here is the output after running the application.
 *   ---------------------------------------------------------------------------
 *   BeanB1 (0), BeanC1 (0), BeanC3 (0), BeanB4 (0), BeanB4 (1), BeanB4 (2), BeanB4 (3), BeanB4 (4), BeanB4 (5), BeanB3 (0)
 *   ---------------------------------------------------------------------------
 *   - BeanB1 (0) is directly generated by the configuration XML file.
 *   - BeanC1 (0) and BeanC3 (0) are directly generated by the configuration Java file (the "basePackages" attribute of the @ComponentScan annotation).
 *   - BeanB4 (0), BeanB4 (1), BeanB4 (2), BeanB4 (3), BeanB4 (4) and BeanB4 (5) are directly generated by the BeanC3 Java file (the methods annotated by the @Bean annotation).
 *   - BeanB3 (0) is directly generated by the configuration Java file (the method annotated by the @Bean annotation).
 * </pre>
 */
public class BeanA {

	@Autowired(required = false)
	private List<CommonBean> beans;

	public void doSomething() {
		System.out.println(getClass().getSimpleName());
		System.out.println();

		System.out.println("beans: " + beans);
		if (beans != null) {
			System.out.println("beans.size(): " + beans.size());
			for (CommonBean bean : beans) {
				System.out.println(bean);
			}
		}
	}

	public static void main(String[] args) {
		BeanA bean = new BeanA();
		bean.doSomething();
	}

}
